"""Generate Wazuh rules for Cowrie's JSON log from the project's own ATT&CK rules.

Wazuh's built-in ``json`` decoder already turns each Cowrie line into fields
(``eventid``, ``src_ip``, ``username``, ``input`` ...), so no custom decoder is needed.
Only rules are generated, and they come from two places:

* session-level rules written here (logins, brute force, transfers, tunnels), and
* one rule per command rule in ``rules.toml``, so the SIEM and the database always
  agree on what is suspicious. ``surya-kundal wazuh-rules`` regenerates the file and
  a test fails if the committed copy drifts.

Differences from the Python mapping engine, stated plainly: Wazuh cannot split a
command line into pieces, so ``segment`` rules run on the whole line, and Wazuh raises
only the first matching rule per event, so high-confidence rules are listed first.
To compensate for the first, a leading ``^`` in segment patterns also matches after
``;``, ``&&``, ``|`` and ``sudo``/``env`` wrappers.
"""

from __future__ import annotations

import re
from xml.sax.saxutils import escape

from surya_kundal.mapping.engine import DEFAULT_USERNAMES, load_rules

BASE_ID = 100500
COMMAND_BASE = 100520
COMMAND_RULES_START = 100600
LEVELS = {"low": 4, "medium": 7, "high": 10}
CONFIDENCE_ORDER = {"high": 0, "medium": 1, "low": 2}

_HEADER = """\
<!--
  Surya Kundal: Wazuh rules for Cowrie's JSON log.
  GENERATED by `surya-kundal wazuh-rules` from rules.toml. Do not edit by hand;
  edit rules.toml and regenerate. Rule IDs 100500-100599 are session-level,
  100600+ are command rules (IDs follow rules.toml order; append, never reorder).
-->
"""


def _mitre(*ids: str) -> str:
    return "<mitre>" + "".join(f"<id>{i}</id>" for i in ids) + "</mitre>"


def _rule(
    rule_id: int,
    level: int,
    description: str,
    *,
    conditions: tuple[str, ...] = (),
    technique: str | None = None,
    groups: str = "",
    attrs: str = "",
) -> str:
    body = [f"    {c}" for c in conditions]
    body.append(f"    <description>{escape(description)}</description>")
    if technique:
        body.append(f"    {_mitre(technique)}")
    if groups:
        body.append(f"    <group>{groups}</group>")
    return f'  <rule id="{rule_id}" level="{level}"{attrs}>\n' + "\n".join(body) + "\n  </rule>"


def _event(event_id: str) -> str:
    return f'<field name="eventid" type="osmatch">^cowrie.{event_id}$</field>'


def session_rules() -> list[str]:
    defaults = "|".join(sorted(DEFAULT_USERNAMES))
    return [
        _rule(
            BASE_ID,
            0,
            "Cowrie honeypot event",
            conditions=(
                "<decoded_as>json</decoded_as>",
                '<field name="eventid" type="osmatch">^cowrie.</field>',
            ),
        ),
        _rule(
            BASE_ID + 1,
            3,
            "Cowrie: connection to the honeypot",
            conditions=(f"<if_sid>{BASE_ID}</if_sid>", _event("session.connect")),
            groups="",
        ),
        _rule(
            BASE_ID + 10,
            5,
            "Cowrie: failed SSH login",
            conditions=(f"<if_sid>{BASE_ID}</if_sid>", _event("login.failed")),
            technique="T1110.001",
            groups="authentication_failed,",
        ),
        _rule(
            BASE_ID + 11,
            8,
            "Cowrie: password guessing, 3+ failed logins from one source in 2 minutes",
            conditions=(
                f"<if_matched_sid>{BASE_ID + 10}</if_matched_sid>",
                "<same_field>src_ip</same_field>",
            ),
            technique="T1110.001",
            groups="authentication_failures,",
            attrs=' frequency="3" timeframe="120"',
        ),
        _rule(
            BASE_ID + 12,
            11,
            "Cowrie: sustained brute force, 10+ failed logins from one source in 5 minutes",
            conditions=(
                f"<if_matched_sid>{BASE_ID + 10}</if_matched_sid>",
                "<same_field>src_ip</same_field>",
            ),
            technique="T1110.001",
            groups="authentication_failures,",
            attrs=' frequency="10" timeframe="300"',
        ),
        _rule(
            BASE_ID + 13,
            8,
            "Cowrie: attacker logged in",
            conditions=(f"<if_sid>{BASE_ID}</if_sid>", _event("login.success")),
            technique="T1078",
            groups="authentication_success,",
        ),
        _rule(
            BASE_ID + 14,
            10,
            "Cowrie: attacker logged in with a default account",
            conditions=(
                f"<if_sid>{BASE_ID + 13}</if_sid>",
                f'<field name="username" type="pcre2">(?i)^({defaults})$</field>',
            ),
            technique="T1078.001",
            groups="authentication_success,",
        ),
        _rule(
            COMMAND_BASE,
            3,
            "Cowrie: attacker ran a command",
            conditions=(f"<if_sid>{BASE_ID}</if_sid>", _event("command.input")),
            groups="",
        ),
        _rule(
            BASE_ID + 30,
            10,
            "Cowrie: file downloaded into the honeypot",
            conditions=(f"<if_sid>{BASE_ID}</if_sid>", _event("session.file_download")),
            technique="T1105",
            groups="malware,",
        ),
        _rule(
            BASE_ID + 31,
            10,
            "Cowrie: file uploaded into the honeypot",
            conditions=(f"<if_sid>{BASE_ID}</if_sid>", _event("session.file_upload")),
            technique="T1105",
            groups="malware,",
        ),
        _rule(
            BASE_ID + 40,
            9,
            "Cowrie: port-forwarding request (the attacker wants to use the host as a relay)",
            conditions=(f"<if_sid>{BASE_ID}</if_sid>", _event("direct-tcpip.request")),
            technique="T1090",
            groups="tunnel,",
        ),
    ]


_START = re.compile(r"(?<!\[)\^")
_SEGMENT_START = r"(?:^|[;&|]\s*)(?:(?:sudo|nohup|env|time|exec)\s+)*"


def wazuh_pattern(pattern: str, scope: str) -> str:
    """Wazuh cannot split a line into commands, so let ``^`` match after ; && | too."""
    if scope != "segment":
        return pattern
    return _START.sub(lambda _: _SEGMENT_START, pattern)


def _command_field(pattern: str, scope: str) -> str:
    return f'<field name="input" type="pcre2">{escape(wazuh_pattern(pattern, scope))}</field>'


def command_rules() -> list[str]:
    """One Wazuh rule per rules.toml entry; high confidence first (first match wins)."""
    numbered = [(COMMAND_RULES_START + i, rule) for i, rule in enumerate(load_rules().rules)]
    numbered.sort(key=lambda pair: (CONFIDENCE_ORDER[pair[1].confidence], pair[0]))
    return [
        _rule(
            rule_id,
            LEVELS[rule.confidence],
            f"Cowrie: {rule.description} [{rule.id}]",
            conditions=(
                f"<if_sid>{COMMAND_BASE}</if_sid>",
                _command_field(rule.pattern.pattern, rule.scope),
            ),
            technique=rule.technique,
            groups="command,",
        )
        for rule_id, rule in numbered
    ]


def generate_rules_xml() -> str:
    rules = session_rules() + command_rules()
    return (
        _HEADER
        + '<group name="cowrie,honeypot,surya_kundal,">\n'
        + "\n\n".join(rules)
        + "\n</group>\n"
    )
